import type { Misconception } from "./types";

const list: Misconception[] = [
  // Integers and signs
  { id: "neg_times_neg_negative", label: "Negative × negative kept negative", message: "Two negatives multiplied make a positive.", explain: "When you multiply (or divide) two negative numbers, the signs cancel. Think of −3 × −4 as 'the opposite of −12', which is +12." },
  { id: "neg_times_pos_positive", label: "Negative × positive made positive", message: "A negative times a positive is negative.", explain: "Only two negatives cancel. When exactly one number is negative, the answer stays negative: +2 × −5 = −10." },
  { id: "ignored_sign", label: "Dropped the sign", message: "A negative times a positive stays negative.", explain: "Work out the size first, then the sign. One negative sign means a negative answer; two mean a positive answer." },
  { id: "all_products_positive", label: "Assumed every product of negatives is positive", message: "Pairs of negatives cancel, but with three negatives one is left over.", explain: "Count the negative signs. An even number of negatives gives a positive answer; an odd number gives a negative answer." },
  { id: "added_instead_of_multiplied", label: "Added instead of multiplying", message: "You added the numbers. Here you multiply.", explain: "Check the operation before you start. The × sign (or a number touching a bracket) means multiply, not add." },
  { id: "added_and_dropped_sign", label: "Added and ignored the sign", message: "You added the sizes and ignored the multiplication.", explain: "This answer comes from adding the sizes of the numbers. Multiply them instead, then decide the sign." },
  { id: "subtracted_instead_of_multiplied", label: "Subtracted instead of multiplying", message: "You subtracted. This question asks you to multiply.", explain: "The question is a multiplication. Subtracting gives a different answer. Multiply the sizes, then decide the sign." },
  { id: "multiplied_instead_of_divided", label: "Multiplied instead of dividing", message: "You multiplied. This question asks you to divide.", explain: "÷ means share into equal groups. Divide the sizes, then apply the sign rule." },
  { id: "subtracted_instead_of_divided", label: "Subtracted instead of dividing", message: "You subtracted. This question asks you to divide.", explain: "Check the operation symbol. ÷ means divide." },
  { id: "added_sizes_kept_sign", label: "Added sizes instead of finding the difference", message: "With different signs, find the difference between the sizes.", explain: "−7 + 3 means start at −7 and move 3 to the right. You end up at −4, not −10." },
  { id: "dropped_sign_of_larger", label: "Lost the sign of the larger number", message: "The answer takes the sign of the number with the larger size.", explain: "When the signs differ, subtract the sizes and keep the sign of the bigger one. In −7 + 3, 7 is bigger and negative, so the answer is negative." },
  { id: "minus_negative_stays_minus", label: "Subtracting a negative treated as subtracting", message: "Subtracting a negative is the same as adding.", explain: "Taking away a debt makes you richer. 5 − (−4) = 5 + 4 = 9." },
  { id: "subtracted_sizes", label: "Subtracted the sizes instead of adding", message: "Two steps down the number line add together.", explain: "−6 − 5 means start at −6 and move 5 further left. You go further below zero, to −11." },
  { id: "dropped_negative", label: "Dropped the negative sign", message: "Check the sign. The answer is below zero.", explain: "You found the right size but lost the sign. Picture the number line: is the answer left or right of zero?" },
  { id: "treated_as_minus_negative", label: "Adding a negative treated as adding", message: "Adding a negative moves you down, not up.", explain: "−2 + (−8) means start at −2 and move 8 to the left, which lands on −10." },
  // Number line
  { id: "lost_negative_sign", label: "Crossed zero without going negative", message: "You found the distance but forgot you crossed zero.", explain: "When you move past zero to the left, the numbers become negative. 5 to the left of 2 is −3." },
  { id: "moved_wrong_direction", label: "Moved the wrong way on the number line", message: "Left means smaller. Check which way you moved.", explain: "On a number line, moving left makes numbers smaller and moving right makes them bigger." },
  { id: "added_sizes_then_negated", label: "Added the sizes then made it negative", message: "Start at 2 and count 5 steps left: you reach −3.", explain: "Count from the starting number, not from zero. 2, 1, 0, −1, −2, −3." },
  { id: "smaller_digit_means_smaller", label: "Read negative numbers by their digits", message: "−2 is closer to zero, so it is bigger than −8.", explain: "For negative numbers, the further from zero, the smaller the number. −8 is smaller than −2." },
  { id: "zero_is_smallest", label: "Thought zero is the smallest number", message: "Zero is bigger than every negative number.", explain: "Negative numbers sit to the left of zero on the number line, so they are all smaller than zero." },
  { id: "ignored_negative_signs", label: "Ignored the negative signs", message: "Look at the signs as well as the digits.", explain: "Negative numbers are less than zero. Ignoring the sign changes which number is biggest or smallest." },
  { id: "bigger_digit_means_bigger", label: "Thought a bigger digit means a bigger negative number", message: "−9 is further below zero than −1, so it is smaller.", explain: "For negative numbers, the closer to zero, the larger the number. −1 is the largest of these." },
  { id: "sign_of_larger_misapplied", label: "Kept the wrong sign", message: "Rising 7 from −3 crosses zero and lands on +4.", explain: "Count up from −3: −2, −1, 0, 1, 2, 3, 4. Seven steps up takes you above zero." },
  // Fractions
  { id: "added_tops_and_bottoms", label: "Added tops and bottoms", message: "You can't add the denominators. Find a common denominator first.", explain: "Fractions must be in the same-sized pieces before you add them. 1/2 + 1/3 = 3/6 + 2/6 = 5/6." },
  { id: "no_common_denominator", label: "Skipped the common denominator", message: "Rewrite both fractions with the same denominator first.", explain: "Change each fraction so the bottoms match, then add or subtract the tops only." },
  { id: "added_denominators_only", label: "Combined the denominators", message: "The denominator tells you the size of the pieces; it isn't added.", explain: "Use a common denominator, then combine the numerators." },
  { id: "subtracted_tops_and_bottoms", label: "Subtracted tops and bottoms", message: "Subtract the numerators only, after matching denominators.", explain: "3/4 − 1/2 = 3/4 − 2/4 = 1/4. The denominator stays the same size." },
  { id: "added_instead_of_subtracted", label: "Added instead of subtracting", message: "This question asks you to subtract.", explain: "Check the sign between the fractions before you combine them." },
  { id: "cross_multiplied", label: "Cross-multiplied", message: "To multiply fractions, multiply top × top and bottom × bottom.", explain: "Cross-multiplying is for comparing or dividing fractions. For multiplying, go straight across: 2/3 × 3/4 = 6/12 = 1/2." },
  { id: "added_instead_of_multiplied_fractions", label: "Added instead of multiplying", message: "This question asks you to multiply the fractions.", explain: "Multiply the numerators together and the denominators together." },
  { id: "multiplied_instead_of_added", label: "Multiplied instead of adding", message: "This question asks you to add.", explain: "Find a common denominator, then add the numerators." },
  // Factors
  { id: "common_factor_not_highest", label: "Found a common factor, not the highest", message: "That divides both, but a larger number does too.", explain: "List the factors of both numbers and pick the biggest one they share." },
  { id: "confused_hcf_lcm", label: "Mixed up factors and multiples", message: "Factors divide into a number; multiples are in its times table.", explain: "The highest common factor is the biggest number that divides both. The lowest common multiple is the smallest number both divide into." },
  { id: "multiplied_numbers_for_lcm", label: "Multiplied the numbers to get the LCM", message: "That's a common multiple, but not the lowest one.", explain: "Multiplying always gives a common multiple, but often not the lowest. Count up the times tables until they meet." },
  { id: "factor_guess", label: "Picked a non-factor", message: "A factor divides exactly, with no remainder.", explain: "Check by dividing. If there's a remainder, it isn't a factor." },
  { id: "confused_factor_multiple", label: "Gave a multiple instead of a factor", message: "That's a multiple, not a factor.", explain: "Factors are smaller than (or equal to) the number and divide into it exactly." },
  { id: "product_only_ignored_sum", label: "Matched the product but not the sum", message: "The numbers must multiply to the constant and also add to the middle number.", explain: "For x² + bx + c, find two numbers that multiply to c and add to b. Check both conditions." },
  { id: "sum_only_ignored_product", label: "Matched the sum but not the product", message: "Those add correctly, but check the product too.", explain: "The pair must satisfy both conditions: the right product and the right sum." },
  // Order of operations
  { id: "left_to_right_ignoring_precedence", label: "Worked left to right", message: "Multiply and divide before you add and subtract.", explain: "Order of operations: brackets, powers, then × and ÷, then + and −. 3 + 4 × 2 = 3 + 8 = 11." },
  { id: "added_all", label: "Added every number", message: "Check each operation symbol.", explain: "Each symbol tells you which operation to do. Read the whole expression before you start." },
  { id: "sign_error_after_division", label: "Changed the sign", message: "6 ÷ 2 = 3, and 20 − 3 = 17.", explain: "Do the division first, then subtract the result from 20." },
  { id: "ignored_division", label: "Skipped the division", message: "Don't skip the ÷ step.", explain: "Every operation in the expression must be done. Divide first, then subtract." },
  { id: "squared_terms_separately", label: "Squared each term separately", message: "(a + b)² is not a² + b².", explain: "Squaring a bracket means multiplying it by itself. (2 + 3)² = 5² = 25, and (x − 2)² = x² − 4x + 4." },
  { id: "doubled_instead_of_squared", label: "Doubled instead of squaring", message: "Squaring means multiplying a number by itself.", explain: "5² = 5 × 5 = 25, not 5 × 2." },
  { id: "bracket_ignored", label: "Ignored the brackets", message: "Work out the bracket first.", explain: "Brackets come first in the order of operations." },
  { id: "ignored_brackets", label: "Ignored the brackets", message: "Work out the bracket first.", explain: "Brackets come first: 2 × (5 − 1) = 2 × 4 = 8." },
  { id: "added_before_multiplying", label: "Added before multiplying", message: "Multiply before you add.", explain: "After the bracket, multiply, then add." },
  { id: "dropped_addition", label: "Dropped a term", message: "Don't forget the last term.", explain: "Every part of the expression contributes to the answer." },
  { id: "sign_error_after_multiplication", label: "Changed the sign", message: "Keep the minus sign.", explain: "10 − 2 × 3 = 10 − 6 = 4." },
  { id: "ignored_multiplication", label: "Skipped the multiplication", message: "Don't skip the × step.", explain: "Every operation counts. Multiply first, then subtract." },
  // Algebra
  { id: "sign_ignored_on_term", label: "Ignored a term's sign", message: "The sign belongs to the term after it.", explain: "Each term carries the sign in front of it. Keep it when you collect like terms." },
  { id: "ignored_minus_x", label: "Forgot that x means 1x", message: "−x is −1x, so 3x − x = 2x.", explain: "A lone x has coefficient 1. Subtracting x takes one x away." },
  { id: "combined_unlike_terms", label: "Combined unlike terms", message: "x terms and plain numbers can't be combined.", explain: "Only like terms combine. Collect the x terms, collect the numbers, and keep them separate." },
  { id: "added_magnitudes", label: "Added sizes ignoring signs", message: "Check the signs before you combine.", explain: "+3 − 7 = −4, not +10." },
  { id: "multiplied_repeated_term", label: "Multiplied a repeated term", message: "x + x + x is 3x, not x³.", explain: "Adding the same term repeatedly counts how many you have. Multiplying a term by itself raises the power." },
  { id: "distribute_first_term_only", label: "Multiplied only the first term", message: "The number outside multiplies everything inside.", explain: "Expanding a(b + c) gives ab + ac. Every term in the bracket is multiplied." },
  { id: "sign_flip_on_second_term", label: "Sign error on the second term", message: "Check the sign of the second product.", explain: "Multiply each term including its sign. 3 × −4 = −12." },
  { id: "sign_flip_on_first_term", label: "Sign error on the first term", message: "Check the sign of the first product.", explain: "A negative outside the bracket changes the sign of every term inside." },
  { id: "forgot_extra_term", label: "Forgot a term outside the bracket", message: "Don't forget the term outside the bracket.", explain: "Expand the bracket, then collect it with any other terms." },
  { id: "ignored_leading_minus", label: "Ignored the minus in front", message: "The minus in front multiplies every term by −1.", explain: "−(x − 7) = −1 × x + −1 × −7 = −x + 7." },
  { id: "dropped_middle_term", label: "Dropped the middle term", message: "Expanding gives four terms, and the two middle ones combine.", explain: "(x + a)(x + b) = x² + bx + ax + ab. The middle terms combine; they don't disappear." },
  { id: "sign_error_in_middle", label: "Sign error in the middle term", message: "Check the sign when you combine the middle terms.", explain: "Add the two middle terms with their signs: +2x − 5x = −3x." },
  { id: "subtracted_middle_terms", label: "Subtracted the middle terms", message: "Combine the middle terms with their signs.", explain: "−3x − 4x = −7x. Both terms are negative, so they add up to a larger negative." },
  { id: "divided_first_term_only", label: "Divided only one term", message: "Divide every term by the common factor.", explain: "When you take a factor out, each term inside the bracket is divided by it." },
  { id: "wrong_common_factor", label: "Used a factor that doesn't divide every term", message: "The common factor must divide every term exactly.", explain: "Find the highest factor shared by every term, then divide each term by it." },
  { id: "common_factor_not_dividing_all", label: "Factor doesn't multiply back", message: "Expand your answer to check it matches.", explain: "Multiply the bracket back out. If you don't get the original expression, the factorisation is wrong." },
  { id: "swapped_signs", label: "Swapped the signs", message: "Check by expanding: the middle term comes out with the wrong sign.", explain: "Expand your brackets to check. The signs must give the right middle term." },
  { id: "dropped_negative_constant", label: "Lost the negative constant", message: "The constant is negative, so the two numbers have opposite signs.", explain: "If c is negative, one number in the pair is positive and one is negative." },
  { id: "sign_error_in_pair", label: "Sign error in the pair", message: "Check the product and sum with the signs included.", explain: "Write the pair with signs, then check: do they multiply to c and add to b?" },
  // Equations
  { id: "did_same_operation", label: "Did the same operation instead of the inverse", message: "To undo an operation, do the opposite to both sides.", explain: "Undo + with −, × with ÷, and so on. Whatever you do, do it to both sides." },
  { id: "wrong_inverse_sign", label: "Used the wrong inverse", message: "Subtract the constant first, then divide.", explain: "2x + 3 = 11 → 2x = 8 → x = 4." },
  { id: "forgot_to_divide", label: "Forgot to divide", message: "You found 2x. Divide to get x.", explain: "The last step is to divide both sides by the coefficient of x." },
  { id: "ignored_constant", label: "Ignored a term", message: "Deal with every term before dividing.", explain: "Move the constant first, then divide by the coefficient." },
  { id: "moved_term_without_changing_sign", label: "Moved a term without changing its sign", message: "Moving a term to the other side changes its sign.", explain: "'Moving' is really subtracting from both sides. 5x = 3x + 6 becomes 5x − 3x = 6." },
  { id: "moved_constant_without_changing_sign", label: "Moved a number without changing its sign", message: "Moving a number across the equals sign changes its sign.", explain: "Add or subtract it on both sides. −4 on the left becomes +4 on the right." },
  { id: "ignored_bracket_subtraction", label: "Ignored part of the bracket", message: "Expand or divide the whole bracket.", explain: "4(x − 1) = 12 → x − 1 = 3 → x = 4." },
  { id: "roots_equal_factor_constants", label: "Took the bracket numbers as the solutions", message: "The solutions have the opposite sign to the numbers in the brackets.", explain: "If (x + 3) = 0 then x = −3. Each solution makes its bracket equal zero." },
  { id: "dropped_negative_root", label: "Lost a negative solution", message: "Set each bracket to zero and solve it.", explain: "x + 1 = 0 gives x = −1, not x = 1." },
  { id: "thought_answer_is_zero", label: "Thought x is zero", message: "The product is zero, not x. Set each bracket to zero.", explain: "If two things multiply to zero, at least one of them is zero. Solve each bracket = 0." },
  { id: "dropped_x_factor", label: "Missed the x factor", message: "x on its own is a factor too, so x = 0 works.", explain: "x(x − 6) = 0 means x = 0 or x − 6 = 0." },
  { id: "multiplied_constants", label: "Multiplied the bracket numbers", message: "That's the constant term, not a solution.", explain: "Set each bracket equal to zero separately." },
  { id: "added_constants", label: "Added the bracket numbers", message: "Set each bracket to zero separately.", explain: "Each bracket gives its own solution." },
  { id: "forgot_coefficient", label: "Forgot the coefficient of x", message: "2x − 1 = 0 gives x = 1/2.", explain: "After moving the constant, divide by the coefficient of x." },
  { id: "divided_wrong_way", label: "Divided the wrong way", message: "2x = 1 means x = 1 ÷ 2.", explain: "Divide the constant by the coefficient, not the other way round." },
  { id: "wrong_factor_pair", label: "Picked the wrong factor pair", message: "Check that your pair adds to the middle number.", explain: "Factorise first, then set each bracket to zero. Check your solutions by substituting." },
  // Substitution, squares and the formula
  { id: "lost_sign_on_substitution", label: "Lost the sign when substituting", message: "Put negative values in brackets when you substitute.", explain: "3x with x = −2 is 3 × (−2) = −6." },
  { id: "sign_error_on_constant", label: "Sign error on the constant", message: "Check the sign of each term.", explain: "Substitute, then work through each term carefully." },
  { id: "dropped_final_sign", label: "Dropped the final sign", message: "−6 + 5 = −1.", explain: "Different signs: find the difference and keep the sign of the larger size." },
  { id: "squared_without_brackets", label: "Squared without brackets", message: "(−3)² means −3 × −3, which is positive.", explain: "When you square a negative number, the negative is squared too, so the result is positive." },
  { id: "dropped_second_term", label: "Dropped a term", message: "Include every term.", explain: "Substitute into every term of the expression." },
  { id: "sign_errors_both", label: "Sign errors", message: "Bracket each substituted value.", explain: "2 × 4 − 3 × (−1) = 8 + 3 = 11." },
  { id: "squared_coefficient_too", label: "Squared the coefficient too", message: "Only x is squared in 2x².", explain: "2x² means 2 × x². With x = 5: 2 × 25 = 50." },
  { id: "ignored_coefficient", label: "Ignored the coefficient", message: "Don't forget to multiply by 2.", explain: "2x² = 2 × x²." },
  { id: "halved_instead_of_root", label: "Halved instead of square-rooting", message: "A square root is the number that multiplies by itself.", explain: "√81 = 9 because 9 × 9 = 81." },
  { id: "squared_instead_of_root", label: "Squared instead of square-rooting", message: "√ asks for the root, not the square.", explain: "Squaring makes numbers bigger; square-rooting undoes it." },
  { id: "near_miss_root", label: "Picked a nearby number", message: "Check by squaring your answer.", explain: "Square your answer: does it give the number under the root?" },
  { id: "subtracted_before_squaring", label: "Subtracted before squaring", message: "Powers come before subtraction.", explain: "7² − 3² = 49 − 9 = 40." },
  { id: "ignored_powers", label: "Ignored the powers", message: "Square each number first.", explain: "Powers come before addition and subtraction." },
  { id: "added_before_squaring", label: "Added before squaring", message: "Square first, then add.", explain: "(−3)² + 1 = 9 + 1 = 10." },
  { id: "added_roots", label: "Rooted each factor and added", message: "√(16 × 9) = √16 × √9, which you then multiply.", explain: "√(16 × 9) = 4 × 3 = 12." },
  { id: "forgot_root", label: "Forgot to take the root", message: "Take the square root at the end.", explain: "16 × 9 = 144, and √144 = 12." },
  { id: "sign_error_in_discriminant", label: "Sign error in b² − 4ac", message: "With a negative c, −4ac becomes positive.", explain: "Bracket each value: b² − 4(a)(c). Two negatives multiply to a positive." },
  { id: "forgot_factor_4", label: "Forgot the 4 in 4ac", message: "The discriminant is b² − 4ac.", explain: "Multiply a and c, then multiply by 4." },
  { id: "ignored_4ac", label: "Left out 4ac", message: "You only squared b; subtract 4ac too.", explain: "The discriminant is b² − 4ac." },
  { id: "sign_error_on_b", label: "Sign error on −b", message: "−b means the opposite of b.", explain: "If b = −2, then −b = +2." },
  { id: "formula_arithmetic_slip", label: "Arithmetic slip in the formula", message: "Recheck b² − 4ac and the square root.", explain: "Work step by step: discriminant, square root, then (−b ± √) ÷ 2a." },
  { id: "divided_by_2_not_2a", label: "Divided by 2 instead of 2a", message: "The denominator is 2a.", explain: "With a = 2, divide by 4." },
  { id: "forgot_to_divide_by_2a", label: "Forgot to divide by 2a", message: "Divide the top by 2a.", explain: "x = (−b ± √(b² − 4ac)) ÷ 2a. Don't forget the final division." },
];

export const misconceptions: Record<string, Misconception> = Object.fromEntries(
  list.map((m) => [m.id, m]),
);
